# Generated by Django 2.1.7 on 2019-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/posts/%Y'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Article-Review', 'Article-Review'), ('Book-Review', 'Book-Review'), ('Commentary', 'Commentary'), ('About', 'About')], max_length=30),
        ),
    ]
