# Generated by Django 2.1.7 on 2019-03-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, default='hello', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Author'),
        ),
    ]
