# Generated by Django 2.1.7 on 2019-03-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190313_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Article-Review', 'Article-Review'), ('Book-Review', 'Book-Review'), ('Commentary', 'Commentary'), ('About', 'About')], max_length=30),
        ),
    ]
